remote-week2: Backend Service
lytt925/remote-assignments pull request #2
Opened 2023-10-07 18:31 UTC by lytt925

**1. How did you design the user table schema? Why?**
- 以下是我創建database和table的script，依照要求建立五個欄位。
  - id: 設定為auto_increment使得之後不用傳入就能自動新增
  - name: 不能為null和限制長度
  - email: 不能為null和限制長度，因為需要唯一所以加上unique這個constraint
  - password: varchar設定為hash之後的長度，不能為null
  - create_at: 讓他default就不用額外設定。
```sql
CREATE DATABASE assignment;
USE assignment;
CREATE TABLE user(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(40) NOT NULL UNIQUE ,
  password VARCHAR(72) NOT NULL,
  create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ( id )
);
```

**2. What does the status code mean? Is it a must to use?**
- status code可以讓client知道一個請求發送之後的結果（成功或失敗的原因等等），但是status code不一定要加，加上去會比較好，可以有更好的error handling。

**3. How and what tools did you use to test your APIs?**
- 我用Postman發送get/post request來測試

**4. How and what tools did you sue to make sure the app would not shut down even if you exit the ssh connection?**
我建立linux系統的service來跑node的script，我覺得比起nohup，他可以有一些方便的status檢查工具，log也很完整容易查詢，還可以設定開機自動啟動，不用擔心reboot。

**5. What are the interactions between client, firewall, EC2 and RDS when you send a request to your app server and get the response? You can use sequence diagram to describe it more clearly.**

1. Client對EC2發送http request (port 80)
2. request 通過防火牆，根據在EC2上面inbound rule設定的security group來決定要不要給他通過。
3. EC2上面的App server (寫好的express server)接收到request之後，用query string 或是 body 來query mysql獲得資料。
4. mysql 回傳 app server索取的資料
5. app server 回傳response給client
6. response通過防火牆，根據在EC2上面outbound rule設定的security group來決定要不要給他通過
7. 抵達client
![image](https://github.com/lytt925/remote-assignments/assets/76529228/49a71f57-e15a-4da9-8911-06c927e0f1ad)

**6. What did you do to make clients access your APIs without the certain port nubmer?**

- I just start my node server on port 80. AWS EC2 inbound rule should also be modified to allowed HTTP requests from anywhere.

** 7. Compare to the application server, what's the web server**

- Application server像是用node.js或python建立起來的server，而web server則像是apache, nginx那些。

-

2023-10-08 15:33 UTC, addie-tyc commented
1. 完整 👍
2. 有什麼常用的 status code 嗎？
4. 用 systemd 來跑 app 我沒想過也沒試過，好像滿不錯的 XD
6. 直接跑在 80 有碰到什麼問題嗎？

2023-10-08 15:38 UTC, addie-tyc requested changes
code 看起來沒問題，能夠連到你 app 服務的 url 記得貼上來喔～

2023-10-08 15:43 UTC, addie-tyc requested changes

2023-10-08 15:43 UTC, addie-tyc commented on week 2/myapp/index.js
> +  const requestDate = req.header('Date');
endpoint 是 `users`、header 裡面的是 `Request-Date`

2023-10-08 15:43 UTC, addie-tyc commented on week 2/myapp/index.js
> +          "request-date": new Date().toUTCString()
這邊也直接從 header 拿就可以囉

2023-10-08 17:38 UTC, lytt925 commented
> ~code 看起來沒問題，能夠連到你 app 服務的 url 記得貼上來喔～~ 我從截圖拿到你的網址了，之後請記得附上囉，另外，有一些格式上的錯誤喔！

url我有放在repo的README裡面～
那個header的request date 我有試過，但好像沒有，我再試一次。

2023-10-08 17:59 UTC, lytt925 commented
> 1. 完整 👍
> 2. 有什麼常用的 status code 嗎？

200 OK：表示請求成功
204 No Content：表示伺服器已成功處理請求，但不需要返回任何內容，通常用於DELETE請求。
400 Bad Request：表示client的請求無效，伺服器無法理解或處理。
401 Unauthorized：表示client需要進行身份驗證才得到請求的資源。
403 Forbidden：表示伺服器理解請求，但拒絕提供所請求的資源的權限。
404 Not Found：表示所請求的資源不存在於伺服器上。
409 Conflit：請求導致了衝突，所以無法處理client的請求。
500 Internal Server Error：表示伺服器在處理請求時遇到了內部錯誤，通常是伺服器出現問題時返回。
503 Service Unavailable：表示伺服器暫時無法處理請求，通常是由於伺服器過載或維護而導致。

> 3. 用 systemd 來跑 app 我沒想過也沒試過，好像滿不錯的 XD

可以直接利用systemctl restart/stop/status myapp來做一些操作還不錯。
或是journalctl -eu myapp來看log

> 4. 直接跑在 80 有碰到什麼問題嗎？

需要root權限，而root用的node太舊（因為access不到我用nvm的node）所以跑不起來。
後來上網查後，我建立symbolic link把nvm的node連到/usr/local/bin/node就可以正常跑了。

2023-10-09 14:57 UTC, addie-tyc commented
好，我知道你的 url 在 README 裡面了，但作業有要求要提供在 PR 裡喔 XD
使用 root 來執行 app 會有什麼問題嗎？

2023-10-09 15:01 UTC, addie-tyc approved these changes
code 的修正沒問題，測試也 ok，本週作業沒問題！root 執行的議題可以再研究看看

2023-10-09 15:48 UTC, merged

2023-10-09 15:49 UTC, lytt925 commented
> 好，我知道你的 url 在 README 裡面了，但作業有要求要提供在 PR 裡喔 XD 使用 root 來執行 app 會有什麼問題嗎？

OK，這我再研究看看
謝謝～